CREATE TABLE IF NOT EXISTS `model_call_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `shop_id` bigint NOT NULL,
  `user_id` bigint DEFAULT NULL,
  `username` varchar(128) DEFAULT NULL,
  `provider_code` varchar(64) NOT NULL,
  `model_name` varchar(128) NOT NULL,
  `prompt_code` varchar(128) DEFAULT NULL,
  `prompt_version` varchar(64) DEFAULT NULL,
  `trace_id` varchar(128) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `report_id` bigint DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `prompt_tokens` int DEFAULT NULL,
  `completion_tokens` int DEFAULT NULL,
  `total_tokens` int DEFAULT NULL,
  `latency_ms` bigint DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `prompt_preview` text DEFAULT NULL,
  `output_preview` text DEFAULT NULL,
  `metadata_json` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_shop_created` (`tenant_id`, `shop_id`, `created_at`),
  KEY `idx_provider_model` (`provider_code`, `model_name`),
  KEY `idx_status` (`status`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Model call log';
