INSERT INTO `mcp_tool` (
  `tenant_id`, `tool_code`, `tool_name`, `category`, `description`,
  `input_schema`, `output_schema`, `permission_code`, `risk_level`,
  `need_approval`, `idempotent`, `timeout_ms`, `retry_count`,
  `connector_code`, `enabled`, `version`, `owner`, `created_at`, `updated_at`
) VALUES
(NULL, 'order.query_detail', 'Order Detail Query', 'order', 'Query representative order details for operations investigation.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["orders"]}' AS JSON),
  'order:read', 'low', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'order.query_refund_risk', 'Refund Risk Query', 'order', 'Identify refund and after-sales risk orders.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["refundRiskRate","riskOrders"]}' AS JSON),
  'order:read', 'medium', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'comment.analyze_sentiment', 'Comment Sentiment Analysis', 'comment', 'Analyze negative sentiment topics and comment risk drivers.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["negativeRatio","topics"]}' AS JSON),
  'comment:read', 'low', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'comment.create_reply_draft', 'Comment Reply Draft', 'comment', 'Generate customer service reply drafts for risky comments.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["draftId","replyDraft"]}' AS JSON),
  'comment:write', 'medium', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'product.query_low_click', 'Low Click Product Query', 'product', 'Find products with high exposure and low CTR.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["products"]}' AS JSON),
  'product:read', 'low', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'product.optimize_title', 'Product Title Optimization', 'product', 'Generate optimized product title suggestions.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["titleSuggestions"]}' AS JSON),
  'product:write', 'medium', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'product.update_title', 'Product Title Update', 'product', 'High-risk product title update requiring manual approval.',
  CAST('{"type":"object","required":["shopId","productId","newTitle"]}' AS JSON),
  CAST('{"type":"object","required":["productId","newTitle","status"]}' AS JSON),
  'product:write', 'high', 1, 0, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'ad.query_low_roi', 'Low ROI Campaign Query', 'ad', 'Find high-spend low-ROI ad campaigns.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["campaigns"]}' AS JSON),
  'ad:read', 'low', 0, 1, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'ad.suggest_budget', 'Ad Budget Adjustment Suggestion', 'ad', 'High-risk ad budget adjustment suggestion requiring approval.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["budgetChanges"]}' AS JSON),
  'ad:write', 'high', 1, 0, 10000, 0, 'mock.mall', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'report.export_excel', 'Operation Report Excel Export', 'report', 'Export operation report evidence to an Excel workbook.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["exportId","fileName","status"]}' AS JSON),
  'report:export', 'medium', 0, 1, 10000, 0, 'local.excel', 1, '1.0.0', 'platform', NOW(), NOW()),
(NULL, 'feishu.sync_report', 'Feishu Report Sync', 'collaboration', 'Sync operation report summary to a Feishu document.',
  CAST('{"type":"object","required":["shopId"]}' AS JSON),
  CAST('{"type":"object","required":["documentId","documentUrl","status"]}' AS JSON),
  'feishu:write', 'medium', 0, 1, 10000, 0, 'feishu.document', 1, '1.0.0', 'platform', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tool_name` = VALUES(`tool_name`),
  `description` = VALUES(`description`),
  `input_schema` = VALUES(`input_schema`),
  `output_schema` = VALUES(`output_schema`),
  `permission_code` = VALUES(`permission_code`),
  `risk_level` = VALUES(`risk_level`),
  `need_approval` = VALUES(`need_approval`),
  `idempotent` = VALUES(`idempotent`),
  `connector_code` = VALUES(`connector_code`),
  `enabled` = VALUES(`enabled`),
  `updated_at` = NOW();
