CREATE TABLE IF NOT EXISTS `approval_request` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `shop_id` bigint NOT NULL,
  `approval_no` varchar(64) NOT NULL,
  `source_type` varchar(64) NOT NULL,
  `source_id` bigint DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `step_id` bigint DEFAULT NULL,
  `trace_id` varchar(128) DEFAULT NULL,
  `tool_code` varchar(128) DEFAULT NULL,
  `risk_level` varchar(32) NOT NULL,
  `title` varchar(256) NOT NULL,
  `reason` text DEFAULT NULL,
  `input_summary` text DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `requester_id` bigint NOT NULL,
  `requester_name` varchar(128) DEFAULT NULL,
  `approver_id` bigint DEFAULT NULL,
  `approver_name` varchar(128) DEFAULT NULL,
  `decision_comment` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `decided_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_approval_no` (`approval_no`),
  KEY `idx_tenant_shop_status` (`tenant_id`, `shop_id`, `status`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_tool_code` (`tool_code`),
  KEY `idx_risk_level` (`risk_level`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Approval request';
